Release 1
jgnacadja/rintiofrance pull request #8
Opened 2022-05-13 16:41 UTC by lohnsonok

2022-05-18 16:31 UTC, jgnacadja commented on src/components/Contact.vue
> +        onExpire: () => {
Pas la peine d'invoquer des methodes si elle ne génère que des console.log()

2022-05-18 16:32 UTC, jgnacadja commented on src/components/Contact.vue
> +                    "user_Y2KIJGmvuqmYVVqo9JBO8"
Possible d'utiliser des variables d'environnement ?

2022-05-18 16:34 UTC, jgnacadja commented on src/pages/postuler.vue
> +            onExpire: () => {
A l'expiration du token , prévoire une actualisation du component

2022-05-18 17:16 UTC, lohnsonok commented on src/pages/postuler.vue
> +            onExpire: () => {
a l'expiration du token, il refais le captcha avant de soumettre

2022-05-20 10:47 UTC, jgnacadja requested changes

2022-05-20 10:47 UTC, jgnacadja commented on gridsome.config.js
> +  siteUrl: `https:rintio.com`,
rintio.fr

2022-05-20 10:47 UTC, jgnacadja commented on gridsome.server.js
> +  // api.loadSource(({ addCollection }) => {
Pourquoi ? Avons nous besoin ?

2022-05-20 14:49 UTC, lohnsonok commented on gridsome.server.js
> +  // api.loadSource(({ addCollection }) => {
c'est le code par default de gridsome, on a rien ajouter (vous voyer que c'est commenter)

2022-05-23 07:00 UTC, jgnacadja approved these changes

2022-06-29 16:52 UTC, merged